On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    ../0x00-hello_world/.3-name.swp
	deleted:    ../0x00-hello_world/.5-printf.c.swp
	modified:   ../0x00-hello_world/1-compiler
	modified:   ../0x00-hello_world/100-intel
	modified:   ../0x00-hello_world/101-quote.c
	modified:   ../0x00-hello_world/2-assembler
	modified:   ../0x00-hello_world/3-name
	modified:   ../0x00-hello_world/4-puts.c
	modified:   ../0x00-hello_world/5-printf.c
	modified:   ../0x00-hello_world/6-size.c
	modified:   ../0x01-variables_if_else_while/0-positive_or_negative.c
	modified:   ../0x01-variables_if_else_while/1-last_digit.c
	modified:   ../0x01-variables_if_else_while/101-print_comb4.c
	modified:   ../0x01-variables_if_else_while/102-print_comb5.c
	modified:   ../0x01-variables_if_else_while/2-print_alphabet.c
	modified:   ../0x01-variables_if_else_while/3-print_alphabets.c
	modified:   ../0x01-variables_if_else_while/4-print_alphabt.c
	modified:   ../0x01-variables_if_else_while/5-print_numbers.c
	modified:   ../0x01-variables_if_else_while/6-print_numberz.c
	modified:   ../0x01-variables_if_else_while/7-print_tebahpla.c
	modified:   ../0x01-variables_if_else_while/8-print_base16.c
	modified:   ../0x01-variables_if_else_while/9-print_comb.c
	modified:   ../0x02-functions_nested_loops/10-add.c
	modified:   ../0x02-functions_nested_loops/100-times_table.c
	modified:   ../0x02-functions_nested_loops/101-natural.c
	modified:   ../0x02-functions_nested_loops/102-fibonacci.c
	modified:   ../0x02-functions_nested_loops/103-fibonacci.c
	modified:   ../0x02-functions_nested_loops/104-fibonacci.c
	modified:   ../0x02-functions_nested_loops/11-print_to_98.c
	modified:   ../0x02-functions_nested_loops/7-print_last_digit.c
	modified:   ../0x02-functions_nested_loops/8-24_hours.c
	modified:   ../0x02-functions_nested_loops/9-times_table.c
	modified:   ../0x05-pointers_arrays_strings/100-atoi.c
	modified:   ../0x05-pointers_arrays_strings/101-keygen.c
	modified:   ../0x05-pointers_arrays_strings/8-print_array.c
	modified:   ../0x05-pointers_arrays_strings/9-strcpy.c
	modified:   ../0x06-pointers_arrays_strings/0-main.c
	modified:   ../0x06-pointers_arrays_strings/0-strcat.c
	modified:   ../0x06-pointers_arrays_strings/1-main.c
	modified:   ../0x06-pointers_arrays_strings/1-strncat.c
	modified:   ../0x06-pointers_arrays_strings/100-rot13.c
	modified:   ../0x06-pointers_arrays_strings/101-print_number.c
	modified:   ../0x06-pointers_arrays_strings/102-magic.c
	modified:   ../0x06-pointers_arrays_strings/103-infinite_add.c
	modified:   ../0x06-pointers_arrays_strings/104-print_buffer.c
	modified:   ../0x06-pointers_arrays_strings/2-main.c
	modified:   ../0x06-pointers_arrays_strings/2-strncpy.c
	modified:   ../0x06-pointers_arrays_strings/3-main.c
	modified:   ../0x06-pointers_arrays_strings/3-strcmp.c
	modified:   ../0x06-pointers_arrays_strings/4-rev_array.c
	modified:   ../0x06-pointers_arrays_strings/5-string_toupper.c
	modified:   ../0x06-pointers_arrays_strings/6-cap_string.c
	modified:   ../0x06-pointers_arrays_strings/7-leet.c
	modified:   ../0x06-pointers_arrays_strings/README.md
	modified:   ../0x06-pointers_arrays_strings/main.h
	modified:   ../0x07-pointers_arrays_strings/0-memset.c
	modified:   ../0x07-pointers_arrays_strings/1-memcpy.c
	modified:   ../0x07-pointers_arrays_strings/100-set_string.c
	modified:   ../0x07-pointers_arrays_strings/2-strchr.c
	modified:   ../0x07-pointers_arrays_strings/3-strspn.c
	modified:   ../0x07-pointers_arrays_strings/4-strpbrk.c
	modified:   ../0x07-pointers_arrays_strings/5-strstr.c
	modified:   ../0x07-pointers_arrays_strings/7-print_chessboard.c
	modified:   ../0x07-pointers_arrays_strings/8-print_diagsums.c
	modified:   ../0x07-pointers_arrays_strings/README.md
	modified:   ../0x08-recursion/0-puts_recursion.c
	modified:   ../0x08-recursion/1-print_rev_recursion.c
	modified:   ../0x08-recursion/100-is_palindrome.c
	modified:   ../0x08-recursion/101-wildcmp.c
	modified:   ../0x08-recursion/2-strlen_recursion.c
	modified:   ../0x08-recursion/3-factorial.c
	modified:   ../0x08-recursion/4-pow_recursion.c
	modified:   ../0x08-recursion/5-sqrt_recursion.c
	modified:   ../0x08-recursion/6-is_prime_number.c
	modified:   ../0x09-static_libraries/0-isupper.c
	modified:   ../0x09-static_libraries/README.md
	modified:   ../0x09-static_libraries/libmy.a
	modified:   ../0x09-static_libraries/main.h
	modified:   ../0x0A-argc_argv/0-whatsmyname.c
	modified:   ../0x0A-argc_argv/1-args.c
	modified:   ../0x0A-argc_argv/100-change.c
	modified:   ../0x0A-argc_argv/2-args.c
	modified:   ../0x0A-argc_argv/3-mul.c
	modified:   ../0x0A-argc_argv/4-add.c
	modified:   ../0x0A-argc_argv/README.md
	modified:   ../0x0B-malloc_free/0-create_array.c
	modified:   ../0x0B-malloc_free/1-strdup.c
	modified:   ../0x0B-malloc_free/100-argstostr.c
	modified:   ../0x0B-malloc_free/101-strtow.c
	modified:   ../0x0B-malloc_free/2-str_concat.c
	modified:   ../0x0B-malloc_free/3-alloc_grid.c
	modified:   ../0x0B-malloc_free/4-free_grid.c
	modified:   0-main.c
	modified:   0-malloc_checked.c
	modified:   1-main.c
	modified:   1-string_nconcat.c
	modified:   2-calloc.c
	modified:   2-main.c
	modified:   3-array_range.c
	modified:   3-main.c
	modified:   main.h
	modified:   ../README.md

no changes added to commit (use "git add" and/or "git commit -a")
